version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - revive

  settings:
    revive:
      rules:
        - name: exported

  exclusions:
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
