version: 1
root: .
name: snip
default_profile: full
output:
  dir: /home/darius/tmp
  pattern: snip_{profile}_{ts}_{gitsha}.md
  latest: ""
  stdout_default: false
render:
  format: md
  newline: |4+
  code_fences: true
  include_tree: true
  tree_depth: 4
  include_manifest: true
  manifest:
    group_by_slice: true
    include_line_counts: true
    include_byte_counts: true
    include_truncation_notes: true
    include_unreadable_notes: true
  file_block:
    header: "===== FILE: {path} ====="
    footer: ""
budgets:
  max_chars: 10000000
  per_file_max_lines: 600
  per_file_max_bytes: 262144
  drop_policy: drop_low_priority
ignore:
  use_gitignore: true
  always:
    - .git/**
    - node_modules/**
    - dist/**
    - build/**
    - .venv/**
    - .pytest_cache/**
    - coverage/**
    - target/**
    - .snip/**
  binary_extensions:
    - .png
    - .jpg
    - .jpeg
    - .gif
    - .pdf
    - .zip
    - .tar
    - .gz
    - .7z
    - .exe
    - .dll
    - .so
    - .dylib
sensitive:
  exclude_globs:
    - .env*
    - "**/*secret*"
    - "**/*secrets*"
    - "**/*.pem"
    - "**/*.key"
    - "**/id_rsa*"
    - "**/*serviceAccount*.json"
slices:
  api:
    include:
      - cmd/**
      - internal/**
    exclude: []
    priority: 100
  cli:
    include:
      - cmd/**
    exclude: []
    priority: 12
  configs:
    include:
      - "**/*.ini"
      - "**/*.json"
      - "**/*.toml"
      - "**/*.yaml"
      - "**/*.yml"
    exclude: []
    priority: 15
  docs:
    include:
      - README*
      - ARCHITECTURE*
    exclude: []
    priority: 20
  domain:
    include: []
    exclude: []
    priority: 18
  infra:
    include:
      - .github/**
    exclude: []
    priority: 10
  persistence:
    include: []
    exclude: []
    priority: 14
  schema:
    include: []
    exclude: []
    priority: 25
  scripts:
    include:
      - "**/*.sh"
    exclude: []
    priority: 5
  tests:
    include:
      - "**/*_test.go"
    exclude: []
    priority: 40
profiles:
  api:
    enable:
      - api
      - docs
      - configs
    budgets:
      max_chars: 120000
    render:
      tree_depth: 4
  debug:
    enable:
      - api
      - tests
      - docs
    budgets:
      max_chars: 220000
    render:
      tree_depth: 5
  full:
    enable:
      - api
      - cli
      - configs
      - docs
      - infra
      - scripts
      - tests
    budgets:
      max_chars: 220000
    render:
      tree_depth: 5
  minimal:
    enable:
      - api
    budgets:
      max_chars: 80000
    render:
      tree_depth: 3
  tests:
    enable:
      - tests
      - api
    budgets:
      max_chars: 120000
    render:
      tree_depth: 4
